language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
addons:
  apt:
    packages:
    - libxml2-utils
install:
- pip install docutils
script:
- nosetests --verbose
- grep -r -l ft=rst doc/ | xargs -t -n1 -I{} rst2xml.py --strict {} /dev/null
- xmllint --noout --valid doc/manpages/*.xml

# vim:ts=2 sts=2 sw=2 et
