dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
addons:
  apt:
    packages:
    - libxml2-utils
    - docbook-xml
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install pydiatra $pyflakes
- pip install docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- nosetests --verbose
- python3 -m pydiatra .
- python3 -m pyflakes .
- private/check-rst
- make -C doc/manpages check

# vim:ts=2 sts=2 sw=2 et
