dist: xenial
language: python
jobs:
  include:
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8-dev"
  - python: pypy3
addons:
  apt:
    packages:
    - docbook-xml
    - docbook-xsl
    - libxml2-utils
    - xsltproc
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install pydiatra $pyflakes
- python3 -m pip install docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python3 -m nose --verbose
- python3 -m pydiatra .
- python3 -m pyflakes .
- private/check-rst
- make -C doc/manpages
- make -C doc/manpages check

# vim:ts=2 sts=2 sw=2 et
