language: python
python:
- "2.6"
- "2.7"
- "pypy"
addons:
  apt:
    packages:
    - libxml2-utils
install:
- pip install docutils
script:
- nosetests --verbose
- grep -r -l ft=rst doc/ | xargs -t -n1 -I{} rst2xml.py --strict {} /dev/null
- xmllint --noout --valid doc/manpages/*.xml

# vim:ts=2 sts=2 sw=2 et
