#!/bin/sh

# Copyright © 2009-2015 Jakub Wilk <jwilk@jwilk.net>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

name=sinntp
if [ $# -ne 1 ]
then
    printf '%s <version>\n' "$0" >&2
    exit 1
fi
if ! [ -d .hg ]
then
    printf '%s requires hg checkout\n' "$0" >&2
    exit 1
fi
set -e -x
pwd="$PWD"
version="$1"
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS="--owner root --group root --mode a+rX --format ustar"
export GZIP="-9 -n"
hg archive -r "$version" "$sourceroot/$name-$version"
cd "$sourceroot"
rm -Rf */.hg*
make -C */doc/manpages/
tar -czf "$pwd/$name-$version.tar.gz" */
rm -Rf "$sourceroot"

# vim:ts=4 sts=4 sw=4 et
