#!/bin/sh
export version=${1:?"no version number provided"}
set -e
set -x
dch -m -v "$version" -u low -c doc/changelog
perl -pi -e 's/<!ENTITY version \047\K[\w.]+/$ENV{version}/' doc/manpages/*.xml
perl -pi -e 's/^__version__ = \047\K[\w.]+/$ENV{version}/' sinntp
